<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>c-wiz_Source textHelHelclearClear source te_595da7</name>
   <tag></tag>
   <elementGuidId>31c22c4b-ab43-4247-bcbd-aa9533835809</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>c-wiz.rm1UF.dHeVVb.UnxENd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div[2]/div[2]/c-wiz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Source textHelHelclearClear source textShow moreShow lessVoice input isn't suppo&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>c-wiz</value>
      <webElementGuid>d60cbd92-2308-40ba-a86b-d5b87b87cfcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsrenderer</name>
      <type>Main</type>
      <value>xuEY0</value>
      <webElementGuid>0c1404d1-88c9-4220-8016-b37269c43759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rm1UF dHeVVb UnxENd</value>
      <webElementGuid>29453602-3cf9-4520-b28c-83f744c4d3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsdata</name>
      <type>Main</type>
      <value>deferred-c12</value>
      <webElementGuid>1b74ba25-db52-421e-91e5-0a5a078e32cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p</name>
      <type>Main</type>
      <value>%.@.&quot;&quot;,&quot;&quot;,&quot;&quot;]</value>
      <webElementGuid>1febf035-a0b8-4a4a-810a-95591a0e9797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>wnKIze</value>
      <webElementGuid>fb62273a-6547-4e92-9cb0-d850278dceec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>fgP5ge:reBGj,fO5Jj;SuwQzc:psubsc;ZJRbqd:R99J9b;PPMpVe:Ro8hud;iRXaId:vQ5fhd,QHu6Rd,g1rTCe,hHjFBe;WUl1Sc:Lt1lf;ETwhqd:ohO51;xlKgVc:sz93Ff;auJseb:IV7LWe;pNe98e:B1XqVb;xFfZGc:fO5Jj;OQcvYd:lXvwxb;sT00Fe:Nrlepe;MFfQNe:XTf7qb;n3ynxb:tQNmWe;k9TsOe:PCDOwc;RRMwLc:Fg8W1e;mG3QHf:OYLrVb;Qz4V0b:hQ7xdc;fBzasf:YoknPd,k5IE8c,Lm5eE;UgEtGb:hQ7xdc;h5CHLc:i5R1S; click:gx3W4c; touchend:Ui18c;h1Uxi:qx6Cqc;PF39hf:gx3W4c;HmXuze:peH7Nc;Pi02re:peH7Nc;FvQNXc:T2uEDc,J6gWY;zOKmBc:rV2CEd,ZQTNrf;NC92Xd:t0GU7d,UbDGRc;XZiffb:MEUYed,ZcXqnb;</value>
      <webElementGuid>496f132e-c226-40c4-b30a-96b8fc178963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-node-index</name>
      <type>Main</type>
      <value>1;0</value>
      <webElementGuid>50bd4892-59ab-452d-8cbe-b0e3c05cb3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsmodel</name>
      <type>Main</type>
      <value>hc6Ubd gxEsw XpsaS</value>
      <webElementGuid>ae12bc06-026d-418d-be8e-023a0a930d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Source textHelHelclearClear source textShow moreShow lessVoice input isn't supported on this browserBusy...Translate by voiceLoading...Listen3 / 5,000Loading...Turn on Virtual KeyboardSelect Input Toolkeyboard</value>
      <webElementGuid>e43b0482-3ab5-462e-af69-8a7d52c36cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;zQTmif SSPGKf kXN2zb BIdYQ&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;ToWKne&quot;]/c-wiz[@class=&quot;MOkH4e iYelWb yF6Zo&quot;]/div[@class=&quot;OlSOob&quot;]/c-wiz[@class=&quot;QsA0jb&quot;]/div[@class=&quot;ccvoYb&quot;]/div[@class=&quot;AxqVh&quot;]/div[@class=&quot;OPPzxe&quot;]/c-wiz[@class=&quot;rm1UF dHeVVb UnxENd&quot;]</value>
      <webElementGuid>9e2f066d-95b1-4316-aa72-17382c050aa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div[2]/div[2]/c-wiz</value>
      <webElementGuid>1d18290a-648c-4a17-ac0f-445ee886598c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Getting translation...'])[1]/following::c-wiz[1]</value>
      <webElementGuid>db5269b2-65ce-4117-af9c-512d518f088c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zulu'])[3]/following::c-wiz[1]</value>
      <webElementGuid>30cef350-cba1-48b9-8043-3da901cd2174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/c-wiz</value>
      <webElementGuid>86990e84-aed6-48b9-95ee-b907b90fe6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//c-wiz[(text() = concat(&quot;Source textHelHelclearClear source textShow moreShow lessVoice input isn&quot; , &quot;'&quot; , &quot;t supported on this browserBusy...Translate by voiceLoading...Listen3 / 5,000Loading...Turn on Virtual KeyboardSelect Input Toolkeyboard&quot;) or . = concat(&quot;Source textHelHelclearClear source textShow moreShow lessVoice input isn&quot; , &quot;'&quot; , &quot;t supported on this browserBusy...Translate by voiceLoading...Listen3 / 5,000Loading...Turn on Virtual KeyboardSelect Input Toolkeyboard&quot;))]</value>
      <webElementGuid>265ccc78-50d3-49fe-91c7-cdd536daa777</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
