<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>3e4c60be-a164-4213-a748-5e41f0e5ae82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ryNqvb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div[2]/div[2]/c-wiz[2]/div/div[6]/div/div/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;مرحبًا&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a7393088-bad4-4e43-9e64-0c390fa92403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ryNqvb</value>
      <webElementGuid>4b210a93-c073-45a9-a1fc-a35fbf309752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>W297wb</value>
      <webElementGuid>c60d4712-4335-4ae6-9718-e2222511fc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>click:Z0znGe,GFf3ac,fbWStc;contextmenu:Nqw7Te,QP7LD; mouseout:Nqw7Te; mouseover:Z0znGe,c2aHje</value>
      <webElementGuid>12d16ca6-1781-4394-9a25-70598f8ef6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>مرحبًا</value>
      <webElementGuid>ff590d1d-6783-4137-89e3-25055ac3b89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;zQTmif SSPGKf kXN2zb BIdYQ&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;ToWKne&quot;]/c-wiz[@class=&quot;MOkH4e iYelWb yF6Zo&quot;]/div[@class=&quot;OlSOob&quot;]/c-wiz[@class=&quot;QsA0jb&quot;]/div[@class=&quot;ccvoYb&quot;]/div[@class=&quot;AxqVh&quot;]/div[@class=&quot;OPPzxe&quot;]/c-wiz[@class=&quot;sciAJc&quot;]/div[@class=&quot;QcsUad BDJ8fb sMVRZe hCXDsb wneUed&quot;]/div[@class=&quot;usGWQd&quot;]/div[@class=&quot;KkbLmb&quot;]/div[@class=&quot;lRu31&quot;]/span[@class=&quot;HwtZe&quot;]/span[@class=&quot;jCAhz JxVs2d ChMk0b&quot;]/span[@class=&quot;ryNqvb&quot;]</value>
      <webElementGuid>5ff8d128-91b2-4516-bec7-2f0d321fa0cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div[2]/div[2]/c-wiz[2]/div/div[6]/div/div/span/span/span</value>
      <webElementGuid>bd9bf8f9-1275-44e6-a58b-a02269ef7953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try again'])[1]/following::span[3]</value>
      <webElementGuid>2b1d0b1c-486a-4af5-8ccc-f49ff4447575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Translation error'])[1]/following::span[4]</value>
      <webElementGuid>99f40635-82af-4beb-9bea-855ab75f7b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مرحبًا'])[2]/preceding::span[1]</value>
      <webElementGuid>bade86eb-5c7c-454d-b170-cdb5986d8abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello'])[4]/preceding::span[2]</value>
      <webElementGuid>a6827ba9-70ef-43e2-b883-db340a7e026c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='مرحبًا']/parent::*</value>
      <webElementGuid>7c8d7095-b817-4ed3-a8c6-2ecb0393c883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/span/span/span</value>
      <webElementGuid>67fc5343-2952-483f-886b-3e8d905de1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'مرحبًا' or . = 'مرحبًا')]</value>
      <webElementGuid>4340f9c1-8097-4e71-ab5e-85fa5595e2f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
