<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_English_VfPpkd-YVzG2b</name>
   <tag></tag>
   <elementGuidId>bffa14f4-a779-4a19-8165-cb98ecc97db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i12 > span.VfPpkd-YVzG2b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i12']/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;English&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fbbdb64c-03c5-43b3-b56f-8fc8951b53db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VfPpkd-YVzG2b</value>
      <webElementGuid>65bdc95d-11b7-4c09-89b6-dcb67a3155fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>ksKsZd</value>
      <webElementGuid>984ba892-2921-4718-b4c3-06c2dcddf1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i12&quot;)/span[@class=&quot;VfPpkd-YVzG2b&quot;]</value>
      <webElementGuid>07bdf8eb-433c-462d-8da0-d9c1894dccf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='i12']/span[3]</value>
      <webElementGuid>4131f02c-8209-4c59-b75f-2833bbdf6803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span[3]</value>
      <webElementGuid>bb2b2406-4af6-4349-b16d-ddbc06e3d325</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
