<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Arabic_VfPpkd-YVzG2b</name>
   <tag></tag>
   <elementGuidId>cb6a0ee1-15f0-4b46-a39a-b24e95afe33e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i17 > span.VfPpkd-YVzG2b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i17']/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Arabic&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5dd5ad1f-9e6b-4e19-b235-eed0e1ea4b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VfPpkd-YVzG2b</value>
      <webElementGuid>04f485ab-e0b1-4aaa-9fe7-8ae4a9f5d8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>ksKsZd</value>
      <webElementGuid>ab8ce8e8-bba0-4c76-a13f-012de93ddf1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i17&quot;)/span[@class=&quot;VfPpkd-YVzG2b&quot;]</value>
      <webElementGuid>d0f4fdfc-096a-4811-b914-a1b47828a1b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='i17']/span[3]</value>
      <webElementGuid>2cc6e459-2f89-4bbd-82f8-8b37939d4722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/span/button[3]/span[3]</value>
      <webElementGuid>5e439f4b-e71b-4d58-881b-5e632e8b707f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
