<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__gb_d (1)</name>
   <tag></tag>
   <elementGuidId>8d8c9fb7-70ad-4f4a-8c2a-f0c48744b994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.gb_d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gbwa']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;تطبيقات Google&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c5b06b0-fe0c-4684-a3df-b6d9067ebf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_d</value>
      <webElementGuid>c3c65295-1805-4010-ad63-ed71cf6b9846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>تطبيقات Google</value>
      <webElementGuid>4b9b6513-fa3c-4976-a399-5edb5cb9d511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com.eg/intl/ar/about/products</value>
      <webElementGuid>b2d5f289-1ada-433f-a0e3-f15b801974ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb8abfc5-0216-4e78-b3b0-f927bb0a4a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46977b97-0bfa-4560-b54a-c58995e92372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>be45dd74-37be-462c-9779-db09e8c46624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gbwa&quot;)/div[@class=&quot;gb_f&quot;]/a[@class=&quot;gb_d&quot;]</value>
      <webElementGuid>74bc3ea2-458e-48f8-b817-75295ef1a9ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gbwa']/div/a</value>
      <webElementGuid>15142200-4852-4a2f-96ab-fc554182d99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صور'])[1]/following::a[1]</value>
      <webElementGuid>7dc6590f-6704-40d3-a7f8-81d7aa821c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gmail'])[1]/following::a[2]</value>
      <webElementGuid>fdc9283d-8743-4da9-86bd-37abe3810e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل الدخول'])[1]/preceding::a[1]</value>
      <webElementGuid>a40b991b-9c41-41fb-84db-a55882c9ed65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختَر العنصر الذي تريد تقديم ملاحظات بشأنه.'])[1]/preceding::a[2]</value>
      <webElementGuid>117ea9d7-951d-4aa5-a1a7-2e9780e042ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com.eg/intl/ar/about/products')]</value>
      <webElementGuid>d0ad971b-d8d8-4c7b-bfef-633287474c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>367176a1-9378-457d-a6d8-34c71630cbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com.eg/intl/ar/about/products']</value>
      <webElementGuid>fcce9d57-931d-4efe-81c6-258c992cc0ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
