<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gmail</name>
   <tag></tag>
   <elementGuidId>0f998fe6-8c05-4d4c-82df-330a0e2f6380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.gb_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gb']/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Gmail&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9aa7003-ee11-4ffe-9319-bb4986e451f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>8d9f5e83-1c35-4246-8030-c80cec755517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_I</value>
      <webElementGuid>d25e68f8-3f07-4456-82f2-4128fdbd0760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Gmail </value>
      <webElementGuid>b7ce41f8-a4ea-48c9-8fd4-5e04ac85a2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pid</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>362d08d7-f40e-47af-9edb-41fa358528c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mail.google.com/mail/&amp;ogbl</value>
      <webElementGuid>a28fed40-ffbc-4d1d-8027-6f5d86d5384d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>72610c8d-95a8-46ac-985f-d8310a0977d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gmail</value>
      <webElementGuid>170687fc-ec13-47fe-a426-96e90cdeb4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_Dd gb_gb gb_rd&quot;]/div[1]/div[@class=&quot;gb_Kd gb_K gb_4f gb_Uf&quot;]/div[@class=&quot;gb_J gb_K&quot;]/a[@class=&quot;gb_I&quot;]</value>
      <webElementGuid>f8278504-53fc-4ceb-869e-16382d82b1e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gb']/div/div/div/div/a</value>
      <webElementGuid>c60ac1e3-4e8e-4102-a927-9b0a2c6c30a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gmail')]</value>
      <webElementGuid>66b5acae-1c8a-47ac-8214-6c9f850b5dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صور'])[1]/preceding::a[1]</value>
      <webElementGuid>d93e0239-afe4-4e35-9733-02dbc1fc55d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل الدخول'])[1]/preceding::a[3]</value>
      <webElementGuid>13e145a3-3b41-45c6-8100-5674be336769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gmail']/parent::*</value>
      <webElementGuid>73e81a27-9e22-4bc0-b9fc-398c99feed13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://mail.google.com/mail/&amp;ogbl')]</value>
      <webElementGuid>784c6a9f-bf85-42f3-b1cf-af4084ae2bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>680a0321-d478-4c4c-a21a-3a3a600c793b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://mail.google.com/mail/&amp;ogbl' and (text() = 'Gmail' or . = 'Gmail')]</value>
      <webElementGuid>f0af8bc4-524c-40a8-a36f-6fcc2ba00730</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
