<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Google_MrEfLc</name>
   <tag></tag>
   <elementGuidId>682cd517-5b0e-4dc5-94e4-fa59ef57a56c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yDmH0d']/c-wiz/div/div/c-wiz/div/div/div[2]/div[2]/div/ul/li[4]/a/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;YouTube&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>04db5fef-4d81-4f98-a0aa-82b6397c313e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MrEfLc</value>
      <webElementGuid>54541c24-9162-4596-a35b-90f19b82823f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;SSPGKf&quot;]/div[@class=&quot;T4LgNb eejsDc&quot;]/div[@class=&quot;kFwPee&quot;]/c-wiz[1]/div[@class=&quot;qWuU9c&quot;]/div[@class=&quot;EHzcec eejsDc&quot;]/div[@class=&quot;v7bWUd&quot;]/div[@class=&quot;o83JEf&quot;]/div[@class=&quot;LVal7b&quot;]/ul[@class=&quot;ngVsM u4RcUd&quot;]/li[@class=&quot;j1ei8c&quot;]/a[@class=&quot;tX9u1b&quot;]/div[@class=&quot;CgwTDb&quot;]/span[@class=&quot;MrEfLc&quot;]</value>
      <webElementGuid>9efaf9db-5971-4612-8e52-88a34d7a7ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Google/iframe__app (2)</value>
      <webElementGuid>0db0da1c-ead9-445c-9f34-7105632e843d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yDmH0d']/c-wiz/div/div/c-wiz/div/div/div[2]/div[2]/div/ul/li[4]/a/div/span</value>
      <webElementGuid>71a26523-38cf-497c-bbc1-ab1dc1098b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/div/span</value>
      <webElementGuid>3159cc44-0d32-49af-9293-e6e6c02d8a9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
